# ---- Development Stage ----
FROM node:24-bookworm

# Arguments
ARG NODE_ENV=development
ENV NODE_ENV="$NODE_ENV"
ENV YARN_CACHE_FOLDER=/root/.yarn/berry/cache

# Set working directory
WORKDIR /app

# Install system dependencies for native modules
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    apt-get update && apt-get install -y \
    python3 \
    make \
    g++ \
    libvips-dev \
    sqlite3 \
    git \
    && rm -rf /var/lib/apt/lists/*

# Copy local code into the container
COPY . .

RUN --mount=type=cache,target=/root/.yarn/berry/cache,sharing=shared \
    --mount=type=cache,target=/app/.yarn/unplugged,sharing=shared \
    corepack enable && corepack prepare yarn@4.9.2 --activate && \
    yarn install --immutable && \
    yarn combine:css

# Expose typical development port
EXPOSE 3000

# Start development server
CMD ["yarn", "start"]
