services:
  app:
    container_name: expressjs-blog
    profiles:
      - build-only
    image: jpoage1/expressjs-blog:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GIT_REPO: ${GIT_REPO:-https://github.com/jpoage1/expressjs-blog.git}
        GIT_COMMIT: ${GIT_COMMIT:-main}
        BUILD_SHA: ${BUILD_SHA:-unknown}

        CONTENT_PATH: /app/content
        CONFIG_PATH: /app/config.toml

        NODE_ENV: production
    environment:
      NODE_ENV: production
      CONTENT_PATH: /app/content
      CONFIG_PATH: /app/config.toml

      SERVER_SCHEMA: http
      SERVER_PORT: 3000
      SERVER_DOMAIN: localhost
      SERVER_ADDRESS: 0.0.0.0 # Listen address

      PUBLIC_SCHEMA: http
      PUBLIC_PORT: 3000
      PUBLIC_ADDRESS: 127.0.0.1

    volumes:
      - ./config.toml:/app/config.toml:Z
      - blog-logs:/var/log/expressjs-blog:Z
      - blog-state:/root/.local/state/expressjs-blog:Z
    restart: always
    command:
      - yarn
      - start

volumes:
  blog-logs:
  blog-state:
  blog-content:
