services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
        CONTENT_PATH: /app/content
        CONFIG_PATH: /app/config.toml
        # GIT_REPO: ${GIT_REPO:-https://github.com/jpoage1/expressjs-blog.git}
        # GIT_COMMIT: ${GIT_COMMIT:-main}
    command:
      - yarn
      - start
    image: jpoage1/express-blog:latest
    environment:
      NODE_ENV: production
      CONTENT_PATH: /app/content
      CONFIG_PATH: /app/config.toml
    volumes:
      - ./config.toml:/app/config.toml:Z
      - ./content:/app/content:Z
      - blog-logs:/var/log/express-blog:Z
      - blog-state:/root/.local/state/express-blog:Z
    ports:
      - "3400:3400"
    restart: always

volumes:
  blog-logs:
  blog-state:
  # app-dev:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #     args:
  #       NODE_ENV: development
  #   environment:
  #     NODE_ENV: development
  #   volumes:
  #     - .:/app
  #     - /app/node_modules:/app/node_modules
  #   ports:
  #     - "3000:3000"
  #   command: ["npm", "run", "dev"]
