{{- if .Values.config.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.nameOverride | default .Chart.Name }}-config
data:
  config.toml: |
    {{ .Values.config.toml | nindent 4 }}
{{- end }}
