{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.nameOverride | default .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.nameOverride | default .Chart.Name }}
  annotations:
    {{- if .Values.tls.enabled }}
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    {{- end }}
    {{- $issuer := .Values.tls.certIssuer | default (or .Values.ingress.tls.certIssuer "") }}
    {{- if $issuer }}
    cert-manager.io/cluster-issuer: {{ $issuer | quote }}
    {{- end }}
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        {{- range .Values.ingress.hosts }}
        - {{ .host }}
        {{- end }}
      secretName: {{ .Values.ingress.tls.secretName | default (printf "%s-tls" (.Values.nameOverride | default .Chart.Name)) }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $.Values.nameOverride | default $.Chart.Name }}
                port:
                  number: {{ $.Values.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
