{{- if .Values.migrations.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.nameOverride | default .Chart.Name }}-migrate
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-upgrade,pre-install
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          command: ["npx", "knex", "migrate:latest"]
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.dbSecret }}
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.dbSecret }}
                  key: DB_PORT
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.dbSecret }}
                  key: DB_DATABASE
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.dbSecret }}
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.dbSecret }}
                  key: DB_PASSWORD
          volumeMounts:
            {{- if .Values.configFile.enabled | default true }}
            - name: config-file
              mountPath: /app/config.toml
              readOnly: true
            {{- end }}
            {{- if .Values.sourceConfig.enabled | default false }}
            - name: source
              mountPath: "/app"
            {{- end }}
      volumes:
        {{- if .Values.configFile.enabled | default true }}
        - name: config-file
          hostPath:
            path: {{ .Values.configFile.hostPath }}
            type: File
        {{- end }}
        {{- if .Values.sourceConfig.enabled | default false }}
        - name: source
          hostPath:
            path: {{ .Values.sourceConfig.hostPath }}
            type: Directory
        {{- end }}
{{- end }}
