{{- if and .Values.tls.enabled .Values.legacySecretGeneration.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-tls
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls.cert | b64enc }}
  tls.key: {{ .Values.tls.key | b64enc }}
  {{- if .Values.tls.bundle }}
  ca-bundle.crt: {{ .Values.tls.bundle | b64enc }}
  {{- end }}
{{- end }}
