{{- if .Values.tls.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-tls
  labels:
    app: {{ .Chart.Name }}
type: kubernetes.io/tls
data:
  tls.crt: {{ required "tls.cert is required when tls.enabled=true" .Values.tls.cert | b64enc }}
  tls.key: {{ required "tls.key is required when tls.enabled=true" .Values.tls.key | b64enc }}
  {{- if .Values.tls.bundle }}
  ca-bundle.crt: {{ required "tls.bundle is required for this service" .Values.tls.bundle | b64enc }}
  {{- end }}
{{- end }}
