classDiagram
    direction TB
    str <|-- TokenMode
    str <|-- AddressProtocol
    str <|-- LogLevel
    str <|-- ExitStatus
    BaseResource <|-- VMStateSchema
    BaseResource <|-- IntegritySchema
    Base <|-- CompilerJobAuditLog
    Base <|-- PersistentUIState
    PromptSchema <|-- PromptSchema
    PromptCreateSchema <|-- PromptCreateSchema
    PromptORM <|-- PromptORM
    PromptController <|-- PromptController
    BaseResource <|-- PromptSchema
    AuditMixin <|-- PromptSchema
    PromptSchema : +flatten_models()
    PromptSchema : +flatten_tiers()
    BaseModel <|-- PromptCreateSchema
    Base <|-- Prompt
    BaseMixin <|-- Prompt
    PromptConfigSchema <|-- Prompt_configSchema
    PromptConfigCreateSchema <|-- Prompt_configCreateSchema
    PromptConfigORM <|-- Prompt_configORM
    PromptConfigController <|-- Prompt_configController
    Prompt_configController : +get_all()
    Prompt_configController : +get_by_id()
    Prompt_configController : +create()
    Prompt_configController : +update()
    BaseResource <|-- Prompt_configSchema
    AuditMixin <|-- Prompt_configSchema
    Prompt_configSchema *-- ResearchTierSchema
    Prompt_configSchema *-- PromptSchema
    Prompt_configSchema *-- ModelSchema
    BaseModel <|-- Prompt_configCreateSchema
    Base <|-- PromptConfig
    BaseMixin <|-- PromptConfig
    PromptPairSchema <|-- Prompt_pairSchema
    PromptPairCreateSchema <|-- Prompt_pairCreateSchema
    PromptPairORM <|-- Prompt_pairORM
    PromptPairController <|-- Prompt_pairController
    BaseResource <|-- Prompt_pairSchema
    AuditMixin <|-- Prompt_pairSchema
    Prompt_pairSchema *-- ConfigSchema
    Prompt_pairSchema *-- ConfigSchema
    BaseModel <|-- Prompt_pairCreateSchema
    Base <|-- PromptPair
    BaseMixin <|-- PromptPair
    LLMModelSchema <|-- Llm_modelSchema
    LLMModelCreateSchema <|-- Llm_modelCreateSchema
    LLMModelORM <|-- Llm_modelORM
    LLMModelController <|-- Llm_modelController
    BaseResource <|-- Llm_modelSchema
    AuditMixin <|-- Llm_modelSchema
    Llm_modelSchema : +validate_tiers()
    Llm_modelSchema : +validate_servers()
    BaseModel <|-- Llm_modelCreateSchema
    Base <|-- LLMModelData
    BaseMixin <|-- LLMModelData
    BaseRouter : +_setup_routes()
    BaseModel <|-- BaseResource
    BaseResource : +transform_to_id_list()
    BaseResource : +transform_to_name_list()
    BaseModel <|-- AuditMixin
    BaseController : +get_all()
    BaseController : +get_by_id()
    BaseController : +create()
    BaseController : +update()
    BaseController : +delete()
    ResearchTierSchema <|-- Research_tierSchema
    ResearchTierCreateSchema <|-- Research_tierCreateSchema
    ResearchTierORM <|-- Research_tierORM
    ResearchTierController <|-- Research_tierController
    BaseResource <|-- Research_tierSchema
    AuditMixin <|-- Research_tierSchema
    BaseModel <|-- Research_tierCreateSchema
    Base <|-- ResearchTier
    BaseMixin <|-- ResearchTier
    ManifestController : +create_from_cpp()
    Llm_serverController : +get_all()
    Llm_serverController : +get_by_id()
    Llm_serverController : +_poll_server()
    Llm_serverController : +_trigger_pull()
    BaseResource <|-- Llm_serverSchema
    Llm_serverSchema : +validate_models()
    BaseModel <|-- Llm_serverCreateSchema
    Base <|-- LLMServer
    BaseMixin <|-- LLMServer
    Wbs_taskController : +get_ready_tasks()
    BaseResource <|-- WBSTaskSchema
    AuditMixin <|-- WBSTaskSchema
    BaseModel <|-- CreateWBSTaskSchema
    BaseResource <|-- UpdateWBSTaskSchema
    Base <|-- WBSTask
    BaseMixin <|-- WBSTask
    WBSPhaseController : +get_ready_tasks()
    BaseResource <|-- WBSPhaseSchema
    AuditMixin <|-- WBSPhaseSchema
    BaseModel <|-- CreateWBSPhaseSchema
    Base <|-- WBSPhase
    BaseMixin <|-- WBSPhase
    ASTSchema <|-- AstSchema
    ASTCreateSchema <|-- AstCreateSchema
    ASTORM <|-- AstORM
    ASTController <|-- AstController
    Base <|-- AST
    BaseMixin <|-- AST
    AST : +ast_json()
    AST : +create_from_code()
    BaseResource <|-- AstSchema
    AuditMixin <|-- AstSchema
    BaseModel <|-- AstCreateSchema
    Compiler_configController : +get_capabilities()
    Base <|-- CompilerConfig
    BaseMixin <|-- CompilerConfig
    CompilerConfig : +inject_columns()
    Base <|-- CompilationTask
    BaseResource <|-- DispatchContext
    BaseResource <|-- CommandPayload
    CommandPayload *-- DispatchContext
    BaseResource <|-- DispatchPayload
    Base <|-- BuildRegistry
    BuildRegistry : +from_payload()
    BaseResource <|-- CommandPayload
    BaseResource <|-- DispatchPayload
    BaseResource <|-- WeightsConfig
    BaseResource <|-- LogicConfig
    BaseResource <|-- ArchConfig
    BaseResource <|-- ControlFlowConfig
    BaseResource <|-- BatchConfig
    AuditMixin <|-- BatchConfig
    BatchConfig *-- WeightsConfig
    BatchConfig *-- LogicConfig
    BatchConfig *-- ArchConfig
    BatchConfig *-- ControlFlowConfig
    BatchConfig *-- TokenMode
    BatchConfig *-- AddressProtocol
    BaseResource <|-- VMStateSchema
    BaseResource <|-- IntegritySchema
    BaseResource <|-- MinerResponse
    MinerResponse *-- List
    str <|-- TokenMode
    str <|-- AddressProtocol
    str <|-- LogLevel
    str <|-- ExitStatus
    Compile_jobController : +dispatch()
    Base <|-- CompileJob
    BaseMixin <|-- CompileJob
    str <|-- JobStatus
    BaseModel <|-- Compile_jobCreateSchema
    BaseResource <|-- Compile_jobSchema
    AuditMixin <|-- Compile_jobSchema
    Compile_jobSchema *-- JobStatus
    ProjectMap : +verify()
    ProjectMap : +get()
    NeuralRequest : +to_ollama_payload()
    HexaNeuralProvider : +dispatch()
    ModelManager : +_pull_worker()
    ModelManager : +get_system_status()
    ChaosEngine : +evaluate_pressure()
    ChaosEngine : +inject()
    BatchGenerator : +generate()
    BatchGenerator : +_emit()
    BatchGenerator : +_gen_block()
    BatchGenerator : +_gen_expr()
    BatchGenerator : +_gen_math_block()
    BatchGenerator : +_gen_branch_block()
    BatchGenerator : +_gen_loop_block()
    BatchGenerator : +_gen_cond()
    TypeMapper : +to_sql()
    TypeMapper : +get_pydantic_field()
    TypeMapper : +to_pydantic_from_str()
    TypeMapper : +to_pydantic()
    TypeMapper : +get_base_py_type()
    HexaVerifier : +decompile_to_list()
    HexaVerifier : +verify_address_stability()
    HexaVerifier : +autonomous_verify()
    HexaCore : +compile_and_run()
    HexaCore : +get_prompt_from_db()
    HexaCore : +ollama()
    HexaCore : +run_saved_job()
    HexaCore : +get_compiler_capabilities()
    HexaCore : +create_job()
    HexaASTSerializer : +serialize()
    HexaASTDeSerializer : +deserialize()
    HexaASTDeSerializer : +to_code()
    MinerSample : +to_jsonl()
    BaseHexaMiner : +_execute_cpp_batch()
    BaseHexaMiner : +generate_single_mission()
    BaseHexaMiner : +format_sample()
    BaseHexaMiner : +run_parallel()
    BaseHexaMiner : +_worker_loop()
    BaseHexaMiner <|-- SyntaxMiner
    SyntaxMiner : +generate_single_mission()
    SyntaxMiner : +format_sample()
    BaseHexaMiner <|-- MutationMiner
    MutationMiner : +generate_single_mission()
    MutationMiner : +_worker_loop()
    MutationMiner : +format_sample()
    MutationMiner <|-- NegativeMiner
    NegativeMiner : +format_sample()
    BaseHexaMiner <|-- MutationMiner
    MutationMiner : +generate_single_mission()
    MutationMiner : +_worker_loop()
    MutationMiner : +format_sample()
    MutationMiner <|-- NegativeMiner
    NegativeMiner : +format_sample()
    BaseHexaMiner <|-- SyntaxMiner
    SyntaxMiner : +generate_single_mission()
    SyntaxMiner : +format_sample()
    Batch : +serialize()
    Batch : +to_object()
    Batch : +generate()
    Batch : +to_mission()
    Batch : +gen_block()
    Batch : +gen_expr()
    Batch : +gen_cond()
    Batch : +_gen_math_block()
    Batch : +_gen_branch_block()
    Batch : +_gen_loop_block()
    Batch *-- BatchConfig
    TextbookArtifact : +persist()
    TextbookArtifact : +write_py()
    TextbookArtifact *-- Batch
    HexaDatasetBuilder : +_run_compiler_batch()
    HexaDatasetBuilder : +generate_batch()
    HexaDatasetBuilder : +_worker_entry()
    HexaDatasetBuilder : +build_parallel()
    HexaDatasetBuilder : +build_batch()
    HexaAgent : +get_vm_state()
    HexaAgent : +run_correction_loop()
    HexaAgent : +save_training_sample()
    HexaAgent : +build_feedback_prompt()
    HexaCLI : +run_tdd()
    HexaCLI : +run_roundtrip()
    HexaCLI : +build_dataset()
    HexaCLI : +execute_logic()
    HexaCLI : +run_verify()
    HexaCLI : +run_batch_gen()
    HexaROIBenchmark : +_estimate_tokens()
    HexaROIBenchmark : +_get_token_count()
    HexaROIBenchmark : +_get_source_metrics()
    HexaROIBenchmark : +_compile_to_hex()
    HexaROIBenchmark : +calculate_reduction()
    HexaROIBenchmark : +benchmark_hex()
    HexaROIBenchmark : +benchmark_b64()
    HexaROIBenchmark : +get_pure_logic()
    HexaROIBenchmark : +benchmark_logic_density()
    Server : +get_uri()
    Server <|-- OllamaServer
    OllamaModel *-- OllamaServer
    BackendExtractor : +get_bases()
    BackendExtractor : +get_methods()
    BackendExtractor : +get_compositions()
    ContextResolver : +resolve_name()
    BackendFormatter : +format_class()
